# Generated by Django 4.2.1 on 2023-08-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='user_email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='weigh',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
