# Generated by Django 4.2.1 on 2023-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_questionnaire_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='user_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
