# Generated by Django 4.2.1 on 2023-08-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questionnaire_often_injury_alter_questionnaire_weigh'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
