# Generated by Django 4.2.1 on 2023-08-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_questionnaire_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='step',
        ),
    ]
