# Generated by Django 4.2.1 on 2023-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_questionnaire_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='often_training',
            field=models.CharField(choices=[('OM', 'one on mounth'), ('OY', 'one on year'), ('O5', 'one on 5 years'), ('NI', "i don't have injury")], default='NI', max_length=255),
        ),
    ]
