# Generated by Django 4.2.1 on 2023-08-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_questionnaire_often_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='often_training',
            field=models.CharField(choices=[('OM', 'one on mounth'), ('OY', 'one on year'), ('O5', 'one on 5 years'), ('NI', "i don't have training")], default='NI', max_length=255),
        ),
    ]
