# Generated by Django 4.2.1 on 2023-08-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_test_order_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('item_id',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='test',
        ),
    ]
