# Generated by Django 4.2.1 on 2023-09-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_item_options_remove_order_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='questionnaire_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
