# Generated by Django 4.2.1 on 2023-09-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_questionnaire_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
