# Generated by Django 4.2.1 on 2023-09-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_questionnaire_often_training'),
        ('orders', '0007_alter_order_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='questionnaire_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='core.questionnaire'),
        ),
    ]
